### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by kriskate** [Perlmint/ya-i18next-webpack-plugin#77]
Hello,

Although I realise you might not be working on this plugin anymore, I'm still hoping I could get some help.

I'm trying to compile webpack, and keep getting this error:
```js
[ERROR]  TypeError: compilation.missingDependencies.push is not a function
    at I18nextPlugin.<anonymous> (/Users/.../project/node_modules/ya-i18next-webpack-plugin/index.js:333:97)
    at step (/Users/.../project/node_modules/ya-i18next-webpack-plugin/index.js:32:23)
    at Object.throw (/Users/.../project/node_modules/ya-i18next-webpack-plugin/index.js:13:53)
    at rejected (/Users/.../project/node_modules/ya-i18next-webpack-plugin/index.js:5:65)
```

versions:
webpack: 5.2.0
i18next: 19.8.3

Is there anything I'm missing? I've added the webpack plugin and initialize for the client.

Thanks!

**Comment by Perlmint** [comment]
Thanks for reporting.
IMO, you did nothing wrong, This plugin is not tested with webpack 5. 😭 I'll check this soon.

**Comment by Perlmint** [comment]
I just published 0.5.0. Now, It will work with webpack5.
I hope it will work on your case.

**Comment by OsvaldasRubavicius** [comment]
Hi @Perlmint , I ran into the same issue. I cannot see 0.5.0 version published in npm: https://www.npmjs.com/package/ya-i18next-webpack-plugin

**Comment by Perlmint** [comment]
@OsvaldasRubavicius Oh... I'm really sorry. I published just now. Now, 0.5.0 is visible in npm. Thanks for reporting 😭.

**Comment by OsvaldasRubavicius** [comment]
> @OsvaldasRubavicius Oh... I'm really sorry. I published just now. Now, 0.5.0 is visible in npm. Thanks for reporting 😭.

Thanks for a quick response! I've upgraded, but I am now running into a different problem:

```
                compilation.missingDependencies.add(resourceDir);
                                                ^
TypeError: Cannot read property 'add' of undefined
    at I18nextPlugin.addTranslations (/project-dir/node_modules/ya-i18next-webpack-plugin/index.js:393:49)
```

**Comment by Perlmint** [comment]
Oh, there is another error I couldn't test. I'll check it soon. Thanks!

But, It should be occurred by configuration mistake, You should specify correct `resourcePath`.

Here is an example.
https://github.com/Perlmint/ya-i18next-webpack-plugin/blob/master/test/basic-test.ts#L49
`translationPath` in there is 'basic'. This will be treated as [`/basic/en/translation.json`](https://github.com/Perlmint/ya-i18next-webpack-plugin/blob/master/test/basic/en/translation.json) - `{{lng}}`, `{{ns}}` are placeholder for language & namespace.

**Comment by Perlmint** [comment]
@OsvaldasRubavicius hmm... I failed to produce an error that you reported. Can you share the code that you tested or testing environments(versions of webpack, i18next / other used webpack plugin)?

**Comment by OsvaldasRubavicius** [comment]
@Perlmint, I am setting resourcePath to the following: 

`${appSrc}/server/modules/{{ns}}/locales/{{lng}}.json`

Basically I am trying to load translation files from multiple locations. I am passing a list of folder names inside "modules" folder as namespaces config parameter.

Webpack version is 4.42.1 
i18next version is 19.4.2

**Comment by Perlmint** [comment]
@OsvaldasRubavicius This plugin has never tested with webpack 4 😭. 0.5.0 is tested with webpack 5. I successfully reproduce your error with webpack 4.
I assume there are many changes in the webpack internally, I cannot say making this plugin working with webpack 4 will be finished shortly. So, I recommend updating webpack to the 5.

**Comment by OsvaldasRubavicius** [comment]
@Perlmint , thanks for looking into this. I'll see if I can upgrade webpack on my project.
